export enum DocumentType {
    SECONDARY_MARKSHEET = "SECONDARY_MARKSHEET",
    SENIOR_SECONDARY_MARKSHEET = 'SENIOR_SECONDARY_MARKSHEET',
    GRADUATION1MARKSHEET = 'GRADUATION1MARKSHEET',
    GRADUATION2MARKSHEET = 'GRADUATION2MARKSHEET',
    GRADUATION3MARKSHEET = 'GRADUATION3MARKSHEET',
    GRADUATION4MARKSHEET = 'GRADUATION4MARKSHEET',
    GRADUATION5MARKSHEET = 'GRADUATION5MARKSHEET',
    GRADUATION6MARKSHEET = 'GRADUATION6MARKSHEET',
    GRADUATION7MARKSHEET = 'GRADUATION7MARKSHEET',
    GRADUATION8MARKSHEET = 'GRADUATION8MARKSHEET',

}